#!/usr/bin/env python3
"""
Sailing Dashboard Build Script.

Compiles modular YAML files and JS components from src/ into build/ artifacts,
and generates build/local-preview/card-configs.js for offline testing.
"""

import json
import os
import shutil
import sys
import yaml

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.join(ROOT_DIR, "src")
BUILD_DIR = os.path.join(ROOT_DIR, "build")
COMMON_JS_DIR = os.path.join(SRC_DIR, "js", "common")

# Prefix used by `$fn` scalars in dashboard YAML (evaluated by plotly-graph /
# ha-yaml-templating at runtime).
FN_PREFIX = "$fn "
# Prefix used by scalar placeholders in dashboard YAML to reference a shared
# JS snippet from src/js/common/ instead of duplicating it inline.
INCLUDE_PREFIX = "$include:"


def strip_leading_line_comments(js_code):
    """Strip a leading block of `//` documentation comment lines.

    src/js/common/*.js files start with a `//` doc-comment block explaining
    what the snippet does (English docs, per project conventions). That
    block is only meant for humans reading the source file — inlining it
    into the `$fn ...` scalar would make the generated dashboard YAML diverge
    from what is actually deployed/live on Home Assistant (which only ever
    saw the bare expression), so it's dropped before wrapping the snippet
    back into a `$fn` value.
    """
    lines = js_code.splitlines()
    i = 0
    while i < len(lines) and lines[i].strip().startswith("//"):
        i += 1
    return "\n".join(lines[i:]).strip()


def load_common_js_snippets():
    """Load all shared JS snippets from src/js/common/ keyed by file stem.

    Each snippet is expected to contain a single JS expression body (e.g. an
    arrow function) that gets wrapped back into a `$fn ...` scalar when
    injected into the dashboard YAML, so the resulting YAML stays equivalent
    to what used to be copy-pasted inline in each section. Leading `//` doc
    comments are stripped so the injected code matches byte-for-byte what
    was previously duplicated inline (and what is live on Home Assistant).
    """
    snippets = {}
    if not os.path.isdir(COMMON_JS_DIR):
        return snippets
    for fname in sorted(os.listdir(COMMON_JS_DIR)):
        if not fname.endswith(".js"):
            continue
        fpath = os.path.join(COMMON_JS_DIR, fname)
        with open(fpath, "r", encoding="utf-8") as f:
            snippets[fname[:-3]] = strip_leading_line_comments(f.read())
    return snippets


def resolve_includes(node, snippets):
    """Recursively replace `$include:<name>` scalar placeholders in-place.

    Walks dicts/lists produced by yaml.safe_load and substitutes any string
    value that equals `$include:<name>` with the shared JS snippet wrapped
    back into a `$fn ...` expression, so multiple sections can reuse the same
    JS code without duplicating it in every YAML file.
    """
    if isinstance(node, dict):
        for key, value in node.items():
            if isinstance(value, str) and value.startswith(INCLUDE_PREFIX):
                name = value[len(INCLUDE_PREFIX):]
                if name in snippets:
                    node[key] = FN_PREFIX + snippets[name]
            else:
                resolve_includes(value, snippets)
    elif isinstance(node, list):
        for i, value in enumerate(node):
            if isinstance(value, str) and value.startswith(INCLUDE_PREFIX):
                name = value[len(INCLUDE_PREFIX):]
                if name in snippets:
                    node[i] = FN_PREFIX + snippets[name]
            else:
                resolve_includes(value, snippets)


def ensure_dirs():
    """Ensure destination directories exist."""
    os.makedirs(os.path.join(BUILD_DIR, "cards"), exist_ok=True)
    os.makedirs(os.path.join(BUILD_DIR, "local-preview"), exist_ok=True)


def build_cards():
    """Copy JS custom cards to build/cards/."""
    src_card = os.path.join(SRC_DIR, "js", "cards", "windy-boat-card.js")
    dst_card = os.path.join(BUILD_DIR, "cards", "windy-boat-card.js")
    if os.path.exists(src_card):
        shutil.copyfile(src_card, dst_card)
        print(f"Built {dst_card}")


def build_sensors():
    """Build build/sensors-sailing.yaml from src/yaml/sensors/*.yaml."""
    sensors_dir = os.path.join(SRC_DIR, "yaml", "sensors")
    open_meteo_path = os.path.join(sensors_dir, "open_meteo.yaml")
    derived_n2k_path = os.path.join(sensors_dir, "derived_n2k.yaml")

    lines = ["# Generated by build.py — DO NOT EDIT MANUALLY\n"]

    if os.path.exists(open_meteo_path):
        with open(open_meteo_path, "r", encoding="utf-8") as f:
            lines.append(f.read().strip())
        lines.append("\n\n")

    if os.path.exists(derived_n2k_path):
        with open(derived_n2k_path, "r", encoding="utf-8") as f:
            lines.append(f.read().strip())
        lines.append("\n")

    dst_path = os.path.join(BUILD_DIR, "sensors-sailing.yaml")
    with open(dst_path, "w", encoding="utf-8") as f:
        f.write("".join(lines))
    print(f"Built {dst_path}")


def build_automations():
    """Build build/automations-sailing.yaml from src/yaml/automations/*.yaml."""
    auto_dir = os.path.join(SRC_DIR, "yaml", "automations")
    dst_path = os.path.join(BUILD_DIR, "automations-sailing.yaml")

    lines = ["# Generated by build.py — DO NOT EDIT MANUALLY\n"]
    for fname in sorted(os.listdir(auto_dir)):
        if fname.endswith(".yaml"):
            fpath = os.path.join(auto_dir, fname)
            with open(fpath, "r", encoding="utf-8") as f:
                lines.append(f.read().strip())
            lines.append("\n\n")

    with open(dst_path, "w", encoding="utf-8") as f:
        f.write("".join(lines).strip() + "\n")
    print(f"Built {dst_path}")


def build_resources():
    """Build build/lovelace-resources.yaml from src/yaml/resources/lovelace-resources.yaml."""
    src_res = os.path.join(SRC_DIR, "yaml", "resources", "lovelace-resources.yaml")
    dst_res = os.path.join(BUILD_DIR, "lovelace-resources.yaml")
    if os.path.exists(src_res):
        shutil.copyfile(src_res, dst_res)
        print(f"Built {dst_res}")


def build_dashboard():
    """Build build/dashboard-sailing.yaml from header and sections."""
    header_path = os.path.join(SRC_DIR, "yaml", "dashboard", "header.yaml")
    sections_dir = os.path.join(SRC_DIR, "yaml", "dashboard", "sections")

    with open(header_path, "r", encoding="utf-8") as f:
        header_data = yaml.safe_load(f)

    sections = []
    for fname in sorted(os.listdir(sections_dir)):
        if fname.endswith(".yaml"):
            fpath = os.path.join(sections_dir, fname)
            with open(fpath, "r", encoding="utf-8") as f:
                sec_data = yaml.safe_load(f)
                if isinstance(sec_data, list):
                    sections.extend(sec_data)
                elif isinstance(sec_data, dict):
                    sections.append(sec_data)

    snippets = load_common_js_snippets()
    resolve_includes(sections, snippets)

    if header_data and "views" in header_data and len(header_data["views"]) > 0:
        header_data["views"][0]["sections"] = sections

    dst_path = os.path.join(BUILD_DIR, "dashboard-sailing.yaml")
    with open(dst_path, "w", encoding="utf-8") as f:
        yaml.dump(header_data, f, sort_keys=False, allow_unicode=True)
    print(f"Built {dst_path}")


def card_to_preview_entry(card, card_type, fname):
    """Build the preview descriptor (tag/title/config) for a single card."""
    if card_type.startswith("custom:"):
        tag = card_type.replace("custom:", "")
    else:
        tag = f"hui-{card_type}-card"

    label = card.get("name") or card.get("heading") or card.get("title") or card.get("entity") or tag
    if card_type == "heading":
        label = f"Heading: {card.get('heading', '')}"
    elif card_type == "glance":
        label = "Glance metrics"

    title = f"{label} ({card_type} from {fname})"
    return {"tag": tag, "title": title, "config": card}


def build_preview_configs():
    """Generate build/local-preview/card-configs.js from dashboard sections.

    Unlike a flat card list, this preserves the real Lovelace layout: each
    source YAML file becomes a `section`, and every top-level grid inside it
    (a `type: grid` card with a `cards:` list) becomes a `grid` with its own
    `column_span`/`columns`, so local-preview/render.js can recreate the same
    grouping and column layout as build/dashboard-sailing.yaml.
    """
    sections_dir = os.path.join(SRC_DIR, "yaml", "dashboard", "sections")
    snippets = load_common_js_snippets()
    preview_sections = []
    preview_cards = []  # flat list kept for backwards-compat consumers

    for fname in sorted(os.listdir(sections_dir)):
        if not fname.endswith(".yaml"):
            continue
        fpath = os.path.join(sections_dir, fname)
        with open(fpath, "r", encoding="utf-8") as f:
            sec_data = yaml.safe_load(f)
            if not sec_data:
                continue
            resolve_includes(sec_data, snippets)
            grid_list = sec_data if isinstance(sec_data, list) else [sec_data]
            section_grids = []
            for grid in grid_list:
                if not isinstance(grid, dict):
                    continue
                is_grid_container = grid.get("type") == "grid" and "cards" in grid
                cards = grid.get("cards", []) if is_grid_container else [grid]
                grid_cards = []
                for card in cards:
                    if not isinstance(card, dict):
                        continue
                    card_type = card.get("type", "")
                    if not card_type:
                        continue
                    entry = card_to_preview_entry(card, card_type, fname)
                    grid_cards.append(entry)
                    preview_cards.append(entry)
                if grid_cards:
                    section_grids.append({
                        "column_span": grid.get("column_span"),
                        "columns": (grid.get("grid_options") or {}).get("columns") if is_grid_container else None,
                        "cards": grid_cards,
                    })
            if section_grids:
                preview_sections.append({
                    "source": fname,
                    "title": fname.replace(".yaml", "").replace("_", " ").title(),
                    "grids": section_grids,
                })

    # Also load apex-wind if defined in JS cards
    apex_js_path = os.path.join(SRC_DIR, "js", "cards", "apex-wind.js")
    if os.path.exists(apex_js_path):
        apex_cfg = {
            "type": "custom:apexcharts-card",
            "cache": False,
            "graph_span": "26h",
            "span": {"start": "minute", "offset": "-2h"},
            "now": {"show": True, "label": "Now", "color": "#ffffff"},
            "header": {"show": True, "title": "Wind — History & Forecast", "show_states": True, "colorize_states": True},
            "apex_config": {
                "chart": {"height": 300, "width": 600},
                "legend": {"position": "bottom"},
                "yaxis": {"min": 0, "decimalsInFloat": 1},
            },
            "series": [
                {
                    "entity": "sensor.wind_data_raymarine_20_442559_pk_a00872849cc8b861a8f51deb51cc1cd2_wind_speed",
                    "name": "Measured (kts)",
                    "type": "area",
                    "color": "#00bcd4",
                    "stroke_width": 2,
                    "fill_raw": "null",
                    "unit": "kts",
                    "show": {"extremas": True},
                },
                {
                    "entity": "sensor.wind_forecast_flat",
                    "name": "Forecast (kts)",
                    "type": "line",
                    "color": "#4fc3f7",
                    "stroke_width": 2,
                    "stroke_dash": 5,
                    "unit": "kts",
                    "data_generator": "const times=entity.attributes.forecast_time||[];const speeds=entity.attributes.forecast_wind||[];const rangeStart=Date.now()-2*3600000;return times.map((t,i)=>[new Date(t+\"Z\").getTime(),Math.round(speeds[i]*10)/10]).filter(p=>p[0]>=rangeStart);",
                },
                {
                    "entity": "sensor.wind_forecast_flat",
                    "name": "Gusts (kts)",
                    "type": "line",
                    "color": "#ff7043",
                    "stroke_width": 1,
                    "stroke_dash": 4,
                    "unit": "kts",
                    "opacity": 0.9,
                    "data_generator": "const times=entity.attributes.forecast_time||[];const gusts=entity.attributes.forecast_gust||[];const rangeStart=Date.now()-2*3600000;return times.map((t,i)=>[new Date(t+\"Z\").getTime(),Math.round(gusts[i]*10)/10]).filter(p=>p[0]>=rangeStart);",
                },
            ],
        }
        apex_entry = {
            "tag": "apexcharts-card",
            "title": "Wind — History & Forecast (apexcharts-card)",
            "config": apex_cfg
        }
        preview_cards.insert(1, apex_entry)
        # Add it as its own single-card grid right after the wind section
        # (or as a standalone section if no sections were built at all).
        wind_section = next((s for s in preview_sections if s["source"].endswith("wind.yaml")), None)
        target_grids = wind_section["grids"] if wind_section else None
        if target_grids is None:
            preview_sections.append({"source": "apex-wind.js", "title": "Wind (apexcharts-card)", "grids": []})
            target_grids = preview_sections[-1]["grids"]
        target_grids.append({"column_span": None, "columns": None, "cards": [apex_entry]})

    js_content = "// Generated automatically by build.py — DO NOT EDIT MANUALLY\n\n"
    js_content += f"window.PREVIEW_SECTIONS = {json.dumps(preview_sections, indent=2)};\n"
    js_content += f"window.PREVIEW_CARDS = {json.dumps(preview_cards, indent=2)};\n"

    dst_path = os.path.join(BUILD_DIR, "local-preview", "card-configs.js")
    with open(dst_path, "w", encoding="utf-8") as f:
        f.write(js_content)
    print(f"Built {dst_path}")

    # Also sync to local-preview/card-configs.js for local development convenience
    local_preview_dst = os.path.join(ROOT_DIR, "local-preview", "card-configs.js")
    if os.path.exists(os.path.dirname(local_preview_dst)):
        with open(local_preview_dst, "w", encoding="utf-8") as f:
            f.write(js_content)
        print(f"Synced {local_preview_dst}")


def main():
    """Main build entry point."""
    print("Starting sailing-dash build...")
    ensure_dirs()
    build_cards()
    build_sensors()
    build_automations()
    build_resources()
    build_dashboard()
    build_preview_configs()
    print("Build completed successfully!")


if __name__ == "__main__":
    main()
